// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package appkit

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ErrorIcon() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"40\" height=\"40\" viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20.0001 1.53845C9.82088 1.53845 1.53857 9.82076 1.53857 20C1.53857 30.1792 9.82088 38.4615 20.0001 38.4615C30.1793 38.4615 38.4617 30.1792 38.4617 20C38.4617 9.82076 30.1793 1.53845 20.0001 1.53845Z\" fill=\"#C92D45\"></path> <circle cx=\"20.0001\" cy=\"20\" r=\"15.3846\" stroke=\"white\" stroke-opacity=\"0.4\" stroke-width=\"0.923077\"></circle> <path d=\"M18.2695 11.7646C18.2695 10.8093 19.0448 10.0339 20.0001 10.0339C20.9554 10.0339 21.7308 10.8093 21.7308 11.7646V21.3153C21.7308 22.2706 20.9554 23.0459 20.0001 23.0459C19.0448 23.0459 18.2695 22.2706 18.2695 21.3153V11.7646ZM20.0001 30.1923C18.7264 30.1923 17.6926 29.1562 17.6926 27.8848C17.6926 26.6133 18.7264 25.5773 20.0001 25.5773C21.2739 25.5773 22.3076 26.6133 22.3076 27.8848C22.3076 29.1562 21.2739 30.1923 20.0001 30.1923Z\" fill=\"white\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
